name: Release

permissions: read-all

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
    name: Release
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      - run: nix-shell --run 'goreleaser --clean'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}