name: Release

permissions: read-all

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
    name: Release
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b
      - run: nix-shell --run 'goreleaser --clean'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}