name: Release

permissions: read-all

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
    name: Release
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9
      - run: nix-shell --run 'goreleaser --clean'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}