name: Release

permissions: read-all

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
    name: Release
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28
      - run: nix-shell --run 'goreleaser --clean'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}